live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 6, y = 6 }
decorations = "None"
opacity = 0.75

[font]
normal = { family = "Fira Code", style = "Regular" }
size = 11

[cursor]
style = { shape = "Beam", blinking = "Off" }

[mouse]
hide_when_typing = true
